# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"

# Site Settings
lang: en-US
title: Siby Abin's Technology Blog
email: sibyabin@gmail.com
description: "Technology blog by Siby Abin - Senior Data Engineer. Talks about #dataengineering, #cloud, #aws, #spark, #python, #databricks, #airflow and more"
baseurl: ""
url: "https://blogs.sibyabin.tech"
repository: "sibyabin/sibyabin.github.io"
copyright: "© 2023-Siby Abin Thomas. All rights reserved."
author:
  name: Siby Abin Thomas
  twitter: sibyoncloud
  picture: /assets/images/sibyabin.png
twitter_username: sibyoncloud
youtube_username: sibyoncloud
github_username: sibyabin
linkedin_username: sibyabin
logo: /assets/images/icon-small.jpg
google_analytics: 
disqus:
  shortname: sibyabin
search: true
search_full_content: true
search_provider: lunr
algolia:
  application_id: '7GP76N1RA3'
  index_name: blogindex
  search_only_api_key: f973de4bdb68c99b2c3901695d548921
  powered_by: # true (default), false

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
timezone: Asia/Kolkata # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins
plugins: # previously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme

# Jekyll Feed
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - vendor/

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
      share: true 
      related: true
      author_profile: true
  # _recipes
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      read_time: true
  